name: objectbox
version: 0.10.0
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox is a super-fast NoSQL ACID compliant object database.

environment:
  #  sdk: '>=2.12.0-0 <3.0.0'
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  # take care updating flatbuffers - keep aligned with other bindings
  # currently using a forked version in lib/flatbuffers, except for tests (see dev_dependencies)
  # flat_buffers: 1.12.0
  ffi: ^0.1.3
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator:
    path: generator
  pedantic: ^1.10.0-nullsafety.0
  test: ^1.16.0-nullsafety.0
  ffigen: ^1.1.0
  flat_buffers: 1.12.0

ffigen:
  name: 'ObjectBoxC'
  description: 'Bindings to ObjectBox C-API'
  output: 'lib/src/bindings/objectbox-c.dart'
  headers:
    entry-points:
      - 'lib/src/bindings/objectbox.h'
    include-directives:
      - '**objectbox.h'
  enums:
    member-rename:
      '(.*)': # Matches any enum.
        # Removes anything before the first '_', i.e. OBXOrderFlags_CASE_SENSITIVE becomes CASE_SENSITIVE.
        '[^_]+_(.*)': '$1'
  # add location to standard library imports, e.g. stddef.h
  compiler-opts: '-I/usr/lib/clang/11.0.0/include'
  typedef-map:
    'size_t': 'IntPtr'
  preamble: |
    // ignore_for_file: non_constant_identifier_names
