name: objectbox_demo
description: An example project for the objectbox-dart binding.
version: 0.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: any
  intl: any
  objectbox: ^0.10.0
  objectbox_flutter_libs: any

dev_dependencies:
  objectbox_generator: any
  build_runner: ^1.0.0
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

# Note: these overrides are only for ObjectBox internal development, don't use them in your app.
dependency_overrides:
  objectbox:
    path: ../../../../objectbox
  objectbox_generator:
    path: ../../../../generator
  objectbox_flutter_libs:
    path: ../../../../flutter_libs