name: Build and test

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  generator:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Test
        run: ./generator/test.sh

  lib:
    strategy:
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-20.04
        dart:
          - 2.10.5
          # - 2.9.3 - generator stuck. I remember there was an issue in some dependency but don't remember which one.
          - 2.8.4
          - 2.7.2
    runs-on: ${{ matrix.os }}
    steps:
      # Note: dart-sdk from flutter doesn't work on linux, see https://github.com/flutter/flutter/issues/74599
      #      - uses: subosito/flutter-action@v1
      #        with:
      #          flutter-version: 1.22.x
      #      - run: flutter --version
      - uses: cedx/setup-dart@v2
        with:
          version: ${{ matrix.dart }}
      - run: dart --version
      - uses: actions/checkout@v2
      - name: Install ObjectBox C-API
        run: ./install.sh
      - if: startsWith(matrix.os, 'windows')
        run: mv lib/objectbox.dll objectbox/lib/
      - name: Test
        working-directory: objectbox
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ../tool/pub.sh run test


  valgrind:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Install Valgrind
        run: |
          apt update
          apt install -y valgrind
      - name: Test
        working-directory: objectbox
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ./tool/valgrind.sh
